version: '3.8'

services:
  the_boys_db_server:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "p@ssword" # Correct key name is SA_PASSWORD (or MSSQL_SA_PASSWORD also works)
    ports:
      - "1433:1433"
    volumes:
      - sqlserverdata:/var/opt/mssql
    networks:
      - my-network

volumes:
  sqlserverdata:

networks:
  my-network:
    driver: bridge